name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # LTS (evita incompatibilidades do Next com Node 22)
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Build & Export static Next.js
        env:
          # Se o site for servido em /site, mantenha isso; senão, remova.
          NEXT_PUBLIC_BASE_PATH: /site
        run: |
          npx next build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # <-- identação corrigida
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
